defmodule Kyber.Plugin.LLM.PromptBuilder do
  @moduledoc """
  System prompt construction and message building for the Anthropic API.

  Handles:
  - System prompt assembly from vault (SOUL.md, MEMORY.md, daily notes)
  - Knowledge context injection
  - User message construction (text + image attachments)
  - Conversation history formatting
  - Memory reinforcement from response content
  """

  require Logger

  # ── Public: Message building ──────────────────────────────────────────────

  @doc """
  Build the messages list for an Anthropic API call from effect data.

  Effect data may include:
  - `"history"` — list of prior message maps `%{role, content}`
  - `"text"` — current user message
  - `"attachments"` — list of attachment maps with `"url"` and `"content_type"`
  - `"messages"` — explicit messages list (overrides history+text)

  When `"attachments"` contains image entries (content_type starting with `"image/"`),
  the user message content is built as a list of Anthropic content blocks (image + text).
  Otherwise content is a plain string.
  """
  @spec build_messages(map()) :: [map()]
  def build_messages(payload) do
    cond do
      is_list(payload["messages"]) ->
        payload["messages"]

      is_binary(payload["text"]) ->
        history = build_history_messages(payload["history"] || [])
        content = build_user_content(payload["text"], payload["attachments"] || [])
        history ++ [%{"role" => "user", "content" => content}]

      true ->
        []
    end
  end

  @doc """
  Build user-message content for the Anthropic API.

  If the payload has image attachments, returns a list of content blocks:
    [image_block, ..., %{"type" => "text", "text" => text}]
  Otherwise returns the plain text string (more efficient for text-only turns).
  """
  def build_user_content(text, attachments) when is_list(attachments) do
    image_blocks =
      attachments
      |> Enum.filter(fn att ->
        content_type = Map.get(att, "content_type", "")
        String.starts_with?(content_type, "image/")
      end)
      |> Enum.map(fn att ->
        %{"type" => "image", "source" => %{"type" => "url", "url" => att["url"]}}
      end)

    case {image_blocks, text} do
      {[], _} -> text
      {imgs, t} when t == "" or is_nil(t) -> imgs
      {imgs, t} -> imgs ++ [%{"type" => "text", "text" => t}]
    end
  end

  def build_user_content(text, _), do: text

  # ── Public: System prompt ─────────────────────────────────────────────────

  @doc """
  Build the system prompt by combining SOUL.md with vault context.

  Loads:
  1. SOUL.md identity (from vault or file fallback)
  2. Long-term memory (MEMORY.md, auto-curated by Memory.Consolidator)
  3. Today's memory note (if present in vault)
  """
  def build_system_prompt(_chat_id) do
    # Step 1: Load SOUL.md — prefer vault, fall back to file
    soul_content =
      case safe_knowledge_call({:get_tiered, "identity/SOUL.md", :l2}) do
        {:ok, %{body: body}} when is_binary(body) and body != "" -> body
        _ -> load_soul_from_file()
      end

    # Step 2: Long-term memory (MEMORY.md, regenerated by Memory.Consolidator)
    long_term_memory =
      case safe_knowledge_call({:get_tiered, "identity/MEMORY.md", :l2}) do
        {:ok, %{body: body}} when is_binary(body) and body != "" ->
          "\n\n## Long-Term Memory (auto-curated)\n#{body}"

        _ ->
          path = Path.expand("~/.kyber/vault/identity/MEMORY.md")

          case File.read(path) do
            {:ok, content} when content != "" ->
              "\n\n## Long-Term Memory (auto-curated)\n#{content}"

            _ ->
              ""
          end
      end

    # Step 3: Today's memory note
    today = Date.to_string(Date.utc_today())

    memory_context =
      case safe_knowledge_call({:get_tiered, "memory/#{today}.md", :l2}) do
        {:ok, %{body: body}} when is_binary(body) and body != "" ->
          "\n\n## Today's Notes\n#{body}"

        _ ->
          ""
      end

    capabilities_note = """

## Your Capabilities

You are a Claude model with vision — you CAN see and analyze images.

**Image workflow:**
- When someone attaches an image to a Discord message, you see it automatically.
- To take a photo: `camera_snap` → `view_image` (to see it) → `send_file` (to post it).
- To look at any image file: `view_image` with the file path.
- IMPORTANT: `camera_snap` only returns a file path. You MUST call `view_image` on that path
  to actually see the photo before describing it. Never describe a photo you haven't viewed.
"""

    vault_instruction = """

## MANDATORY: Check Your Vault First

Before answering ANY question about concepts, ideas, the Groovy Commutator, Wet Math, D₂, \
or shared work: you MUST call `memory_read` on relevant files in `concepts/` BEFORE responding. \
Also call `memory_list` if you're unsure what's there. Your vault is ground truth. \
Do NOT answer from general knowledge or vibes — if it's not in your vault, say so honestly. \
Confabulating a plausible-sounding answer when you have files you didn't check is a failure mode.
"""

    (soul_content || "") <>
      long_term_memory <> memory_context <> capabilities_note <> vault_instruction
  end

  # ── Public: Memory reinforcement ──────────────────────────────────────────

  @tag_stopwords ~w(
    about after again also another archive around based batch because before being
    below build called change changes check class clause common complete config contains
    context create current cycle datum debug defined delta depends depth detail
    direct doing elixir error event example false found function given group guard handle
    handler have here include index inject input inside issue items just keep kind later
    layer level limit local logic match maybe means memory message might model module
    needs never might often only other output parse pattern place point process query
    quite reason reply reset response result return rules serve should since skill some
    stack state still store string struct system table target test their these thing
    this three through times token total toward under until update using value where while
    which within without would write
  )

  @doc """
  Extract tags from LLM response text and reinforce matching memories.

  Only matches words that are at least 5 chars and not in the stopword list.
  Intentionally lightweight: no LLM call, just simple word extraction.
  """
  def reinforce_memories(content) when is_binary(content) and content != "" do
    existing_tags =
      if Process.whereis(Kyber.Memory.Consolidator) do
        Kyber.Memory.Consolidator.get_pool()
        |> Enum.flat_map(fn mem -> mem.tags || [] end)
        |> MapSet.new()
      else
        MapSet.new()
      end

    words =
      content
      |> String.downcase()
      |> String.split(~r/[\s,.\-:;!?()\"'\[\]{}|<>\/\\]+/)
      |> Enum.filter(fn word ->
        len = String.length(word)
        len >= 5 and word not in @tag_stopwords
      end)
      |> Enum.uniq()

    matched =
      if MapSet.size(existing_tags) > 0 do
        Enum.filter(words, &MapSet.member?(existing_tags, &1))
      else
        words
      end

    tags = Enum.take(matched, 20)

    if tags != [] do
      Kyber.Memory.Consolidator.reinforce(tags)
    end
  end

  def reinforce_memories(_), do: :ok

  # ── Public: History building ──────────────────────────────────────────────

  @doc """
  Build the Anthropic-compatible messages list from session history.

  Content may be a plain string OR a list of content blocks (e.g. image + text).
  Both forms are passed through as-is — the Anthropic API accepts either.
  """
  def build_history_messages(history) when is_list(history) do
    Enum.map(history, fn
      %{"role" => role, "content" => content} -> %{"role" => role, "content" => content}
      %{role: role, content: content} -> %{"role" => to_string(role), "content" => content}
      _ -> nil
    end)
    |> Enum.reject(&is_nil/1)
  end

  def build_history_messages(_), do: []

  # ── Private ───────────────────────────────────────────────────────────────

  defp safe_knowledge_call(request) do
    if Process.whereis(Kyber.Knowledge) do
      try do
        GenServer.call(Kyber.Knowledge, request, 2_000)
      catch
        :exit, _ -> nil
      end
    else
      nil
    end
  end

  defp load_soul_from_file do
    paths = [
      Path.expand("~/.kyber/vault/identity/SOUL.md"),
      Path.join(:code.priv_dir(:kyber_beam), "vault/identity/SOUL.md")
    ]

    Enum.find_value(paths, fn path ->
      case File.read(path) do
        {:ok, content} -> content
        _ -> nil
      end
    end)
  end
end
